version: "3.7"
services:
  web:
    container_name: ticketing_container
    image: ticketing:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4006:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - TZ=Asia/Jakarta
